# Generated by Django 2.0 on 2018-11-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=25, verbose_name='nombre')),
                ('categoria', models.CharField(max_length=25, verbose_name='categoria')),
                ('precio', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=10)),
                ('descripcion', models.TextField(default='Descripcion')),
            ],
        ),
    ]
